name: Build API & Web Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
    outputs:
      committed_generated_files:
        value: ${{ jobs.build.outputs.committed_generated_files }}

jobs:
  build:
    name: Build API & Web
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    outputs:
      committed_generated_files: ${{ steps.set_output.outputs.committed_generated_files }}
    permissions:
      contents: write
      actions: write
    steps:
      - 
        if: ${{ env.PAT != '' }} 
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}
      -
        if: ${{ env.PAT == '' }} 
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: './api/go.mod'
          cache-dependency-path: './api/go.sum'
      - run: make build
        working-directory: './api'

      - uses: actions/setup-node@v5
        with:
          cache: 'yarn'
          node-version-file: './web/package.json'
          cache-dependency-path: './web/yarn.lock'
      - run: yarn install
        working-directory: './web'
      - run: yarn build
        working-directory: './web'        

      - 
        if: ${{ env.PAT != '' }} 
        name: Commit generated files
        id: commit
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Commit generated files"
          git push
      
      - id: set_output
        run: echo "committed_generated_files=${{ steps.commit.outcome == 'success' }}" >> $GITHUB_OUTPUT

      
